### ISSUE TITLE
variety bin command linux incompatible

### ISSUE THREAD

**Issue by stefanocudini** [variety/variety-cli#13]
the binary cli create incompatibility with this package:
https://packages.debian.org/search?keywords=variety

having same name in command line PATH

**Comment by JamesCropcho** [comment]
Thanks for writing us, Stefano.

Oh, huh. I had not heard of that package before; interesting. Well, I'm not inclined to change the name of Variety nor the executable `variety`. Therefore I suspect nothing will be done unless you propose a change, other than renaming, which seems like a good idea, or there is a massive outcry.

Again, I did not know about the other Variety; thanks for writing, Stefan. I wish there were a change we could make which would provide advantages without any disadvantages.
