### ISSUE TITLE
how to support use to a authed database? 

### ISSUE THREAD

**Issue by zppro** [variety/variety-cli#8]
i use -u or --u is not works

**Comment by JamesCropcho** [comment]
Hello zppro, I think you should examine using variety outside of variety-cli. I believe this would allow what you want but I'm not positive. The documenation is here: https://github.com/variety/variety.

Let us know if that doesn't do the trick.

James

**Comment by todvora** [comment]
Hi, those long variants (`--username` and `--password`) should work and are forwarded through variety-cli to mongo shell. To support `-u` and `-p`, one small change (#9) has to be done.
